# Generated by Django 3.1.4 on 2020-12-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lile',
            new_name='Like',
        ),
    ]
